#!/usr/bin/env bash
#================================================================
# DESCRIPTION
#   Standard, OS-agnostic automation script to install, configure
#   and start Apache Druid (single-server / micro-quickstart) as
#   a systemd service.
#
#   Distro support : RHEL / CentOS / Rocky / Alma / Amazon Linux
#                     (8, 9, 10 - AppStream or Eclipse Temurin fallback)
#                     Ubuntu / Debian
#   Prereqs        : root privileges, systemd, internet access
#
#   Druid 36.0.0 officially supports Java 17 and 21 only (Java 8/11
#   support was removed in Druid 35). This script installs Java 17
#   where available, falling back to Java 21, and on RHEL/Rocky/Alma
#   10 (which no longer ship versioned OpenJDK packages natively)
#   falls back further to Eclipse Temurin's official repo.
#
# IDEMPOTENCY
#   Safe to re-run. On first run, all interactive answers (volume,
#   metadata store, deep storage, generated passwords) are saved to
#   /etc/druid-install/state.env (mode 600). Later runs load that
#   file instead of re-prompting, and skip re-downloading/re-copying
#   Druid if the currently installed version already matches
#   DRUID_VERSION below. A healthy, already-running druid.service is
#   left untouched rather than restarted. To force fresh prompts and
#   a clean reinstall (e.g. after bumping DRUID_VERSION for an
#   upgrade, or to rotate credentials), run with --reconfigure.
#
# IMPLEMENTATION
#   Author  - EverestDx (standardized/automated version)
#   Version - v5
#     v5: prompt_volume() now accepts either a bare volume name
#         (e.g. 'ausiytic') or a full path (e.g. '/opt/ausiytic' or
#         'ausiytic/') and normalizes it, instead of silently
#         double-prefixing to /opt//opt/ausiytic.
#================================================================

set -euo pipefail
trap 'rc=$?; log "ERROR" "Script aborted at line $LINENO (exit code $rc)"; exit $rc' ERR

#----------------------------------------------------------------
# 0. CONSTANTS / GLOBAL CONFIG
#----------------------------------------------------------------
DRUID_VERSION="36.0.0"
DRUID_TARBALL="apache-druid-${DRUID_VERSION}-bin.tar.gz"
DRUID_DOWNLOAD_URL="https://archive.apache.org/dist/druid/${DRUID_VERSION}/${DRUID_TARBALL}"
DRUID_SERVICE_USER="edxiuser"

# Where saved answers/credentials live across re-runs (idempotency).
STATE_DIR="/etc/druid-install"
STATE_FILE="${STATE_DIR}/state.env"
FORCE_RECONFIGURE="no"
for arg in "$@"; do
    if [ "$arg" == "--reconfigure" ]; then
        FORCE_RECONFIGURE="yes"
    fi
done

# Preferred Java major versions, in order. Druid 36.0.0 officially
# supports 17 and 21 (17 is the project's recommended version).
JAVA_CANDIDATES=(17 21)

# Metadata store, deep storage, and security credentials vary per
# server/project, so they are collected interactively in
# prompt_druid_config() below rather than hardcoded here.

SCRIPT_PWD="$(pwd)"
LOGTIME="$(date +"%F %T")"
FILESTAMP="$(date +"%d%m%Y%H%M")"
ACCESS_LOG="${SCRIPT_PWD}/druid.access.${FILESTAMP}.log"
ERROR_LOG="${SCRIPT_PWD}/druid.error.${FILESTAMP}.log"

log() {
    local level="$1"; shift
    local msg="[$(date +"%F %T")] [${level}] $*"
    if [ "$level" == "ERROR" ]; then
        echo -e "$msg" | tee -a "$ERROR_LOG" >&2
    else
        echo -e "$msg" | tee -a "$ACCESS_LOG"
    fi
}

# Prompt helper: shows a default in brackets, Enter keeps the default.
ask() {
    local prompt="$1" default="$2" varname="$3" secret="${4:-no}"
    local input
    if [ "$secret" == "yes" ]; then
        read -rsp "${prompt} [${default:+default: $default, }press Enter to skip]: " input
        echo ""
    else
        read -rp "${prompt} [default: ${default:-none, press Enter to skip}]: " input
    fi
    printf -v "$varname" '%s' "${input:-$default}"
}

#----------------------------------------------------------------
# STATE FILE (idempotency): load previously saved answers/credentials
# so re-running the script doesn't re-prompt or regenerate passwords.
#----------------------------------------------------------------
STATE_EXISTS="no"

load_state() {
    STATE_EXISTS="no"
    if [ "$FORCE_RECONFIGURE" == "yes" ]; then
        log "INFO" "--reconfigure passed - ignoring any saved state, will re-prompt for all configuration."
        return
    fi
    if [ -f "$STATE_FILE" ]; then
        # shellcheck disable=SC1090
        source "$STATE_FILE"
        STATE_EXISTS="yes"
        log "INFO" "Loaded saved configuration from $STATE_FILE (volume, metadata store, deep storage, credentials). Re-using it. Pass --reconfigure to override."
    fi
}

persist_state() {
    mkdir -p "$STATE_DIR"
    cat > "$STATE_FILE" <<EOF
# Auto-generated by druid_install.sh - DO NOT EDIT BY HAND.
# Reused on subsequent runs to make the script idempotent.
# Delete this file, or re-run with --reconfigure, to force fresh prompts.
VOLUME_NAME="${VOLUME_NAME}"
BASE_PATH="${BASE_PATH}"
METADATA_TYPE="${METADATA_TYPE}"
META_DB_HOST="${META_DB_HOST:-}"
META_DB_PORT="${META_DB_PORT:-}"
META_DB_NAME="${META_DB_NAME:-}"
META_DB_USER="${META_DB_USER:-}"
META_DB_PASS="${META_DB_PASS:-}"
META_DB_URI="${META_DB_URI:-}"
STORAGE_TYPE="${STORAGE_TYPE}"
AZURE_STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT:-}"
AZURE_STORAGE_CONTAINER="${AZURE_STORAGE_CONTAINER:-}"
AZURE_STORAGE_KEY="${AZURE_STORAGE_KEY:-}"
ADMIN_INIT_PASSWORD="${ADMIN_INIT_PASSWORD}"
INTERNAL_CLIENT_PASSWORD="${INTERNAL_CLIENT_PASSWORD}"
INSTALLED_DRUID_VERSION="${DRUID_VERSION}"
EOF
    chmod 600 "$STATE_FILE"
    log "INFO" "Saved configuration to $STATE_FILE (mode 600) for idempotent re-runs"
}

#----------------------------------------------------------------
# 1. ROOT CHECK / SELF-ELEVATION
#----------------------------------------------------------------
# The script can be launched either as root directly, or as a normal
# user - in which case it re-execs itself under sudo, preserving the
# original arguments and interactive TTY (needed for the volume-name
# prompt further down).
if [ "$(id -u)" -ne 0 ]; then
    if ! command -v sudo >/dev/null 2>&1; then
        echo "This script requires root privileges, and 'sudo' is not installed." >&2
        echo "Please install sudo, or re-run this script as the root user." >&2
        exit 1
    fi
    echo "Not running as root - re-executing with sudo (you may be prompted for your password)..."
    exec sudo -E -H bash "$0" "$@"
fi

#----------------------------------------------------------------
# 2. OS DETECTION
#----------------------------------------------------------------
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS_ID="${ID}"
        OS_ID_LIKE="${ID_LIKE:-}"
        OS_VERSION_ID="${VERSION_ID:-unknown}"
    else
        log "ERROR" "Cannot detect OS - /etc/os-release not found."
        exit 1
    fi

    case "$OS_ID" in
        ubuntu|debian)
            PKG_FAMILY="debian"
            ;;
        rhel|centos|rocky|almalinux|amzn|fedora)
            PKG_FAMILY="rhel"
            ;;
        *)
            if [[ "$OS_ID_LIKE" == *"debian"* ]]; then
                PKG_FAMILY="debian"
            elif [[ "$OS_ID_LIKE" == *"rhel"* || "$OS_ID_LIKE" == *"fedora"* ]]; then
                PKG_FAMILY="rhel"
            else
                log "ERROR" "Unsupported OS: $OS_ID"
                exit 1
            fi
            ;;
    esac
    log "INFO" "Detected OS family: $PKG_FAMILY ($OS_ID $OS_VERSION_ID)"
}

#----------------------------------------------------------------
# 3. INSTALL PREREQUISITES (java, wget, tar, curl)
#----------------------------------------------------------------
install_prereqs() {
    log "INFO" "Checking prerequisites (java, wget, tar, curl, perl)..."

    if command -v java >/dev/null 2>&1 && command -v wget >/dev/null 2>&1 \
        && command -v curl >/dev/null 2>&1 && command -v tar >/dev/null 2>&1 \
        && command -v perl >/dev/null 2>&1 && perl -MFindBin -e1 >/dev/null 2>&1; then
        local jv
        jv="$(java -version 2>&1 | head -n1 | grep -oP '"\K[0-9]+' || true)"
        local already_ok=0 v
        for v in "${JAVA_CANDIDATES[@]}"; do
            [ "$jv" == "$v" ] && already_ok=1
        done
        if [ "$already_ok" -eq 1 ]; then
            log "INFO" "java (major ${jv}), perl+FindBin, wget, tar and curl already present and compatible - skipping package installation"
            return
        fi
    fi

    log "INFO" "Installing prerequisites (java, wget, tar, curl, perl)..."
    if [ "$PKG_FAMILY" == "debian" ]; then
        install_java_debian
    else
        if command -v dnf >/dev/null 2>&1; then
            PKG_MGR="dnf"
        else
            PKG_MGR="yum"
        fi
        # perl-FindBin is required by bin/supervise (which start-micro-quickstart
        # calls to launch/monitor all Druid processes). RHEL/Rocky/Alma minimal
        # images - especially el10 - often don't ship it by default, which
        # otherwise fails silently until the very first service start attempt.
        $PKG_MGR install -y wget tar curl perl perl-FindBin >> "$ACCESS_LOG" 2>> "$ERROR_LOG"
        install_java_rhel
    fi

    if ! command -v java >/dev/null 2>&1; then
        log "ERROR" "Java installation failed."
        exit 1
    fi

    verify_java_version
    log "INFO" "Java version: $(java -version 2>&1 | head -n1)"
}

# Debian/Ubuntu: try each candidate OpenJDK version from the native
# repos in order of preference (17, then 21).
install_java_debian() {
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y >> "$ACCESS_LOG" 2>> "$ERROR_LOG"
    # perl is required by bin/supervise (which start-micro-quickstart calls
    # to launch/monitor all Druid processes) - normally preinstalled on
    # Debian/Ubuntu base images, but listed explicitly to be safe.
    apt-get install -y wget tar curl perl >> "$ACCESS_LOG" 2>> "$ERROR_LOG"

    local v
    for v in "${JAVA_CANDIDATES[@]}"; do
        if apt-cache show "openjdk-${v}-jdk" >/dev/null 2>&1; then
            log "INFO" "Installing openjdk-${v}-jdk from native repos"
            apt-get install -y "openjdk-${v}-jdk" >> "$ACCESS_LOG" 2>> "$ERROR_LOG"
            return
        fi
    done

    log "ERROR" "None of the preferred Java versions (${JAVA_CANDIDATES[*]}) are available in the configured apt repos."
    exit 1
}

# RHEL/CentOS/Rocky/Alma/Amazon Linux: try each candidate OpenJDK
# version as a native AppStream/yum package first (works on 8 and 9,
# and 21 works natively on 10 too). If none of the candidates exist
# in the enabled repos (true for Java 17 on RHEL/Rocky/Alma 10 today,
# since the module-stream system was dropped), fall back to Eclipse
# Temurin's official RPM repo.
install_java_rhel() {
    local v pkg

    for v in "${JAVA_CANDIDATES[@]}"; do
        pkg="java-${v}-openjdk"
        if $PKG_MGR list --available "${pkg}" >/dev/null 2>&1; then
            log "INFO" "Found native package ${pkg} - installing"
            $PKG_MGR install -y "${pkg}" "${pkg}-devel" >> "$ACCESS_LOG" 2>> "$ERROR_LOG"
            return
        fi
    done

    log "WARN" "No native java-{${JAVA_CANDIDATES[*]}}-openjdk package in enabled repos - falling back to Eclipse Temurin"

    rpm --import https://packages.adoptium.net/artifactory/api/gpg/key/public >> "$ACCESS_LOG" 2>> "$ERROR_LOG"

    cat > /etc/yum.repos.d/adoptium.repo <<'EOF'
[Adoptium]
name=Adoptium
baseurl=https://packages.adoptium.net/artifactory/rpm/rhel/$releasever/$basearch
enabled=1
gpgcheck=1
gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public
EOF

    for v in "${JAVA_CANDIDATES[@]}"; do
        if $PKG_MGR install -y "temurin-${v}-jdk" >> "$ACCESS_LOG" 2>> "$ERROR_LOG"; then
            log "INFO" "Installed Temurin ${v} JDK from Adoptium repo"
            register_java_alternative "temurin-${v}-jdk"
            return
        fi
        log "WARN" "temurin-${v}-jdk not available from Adoptium for this OS release, trying next candidate"
    done

    log "ERROR" "Could not install any supported Java version (${JAVA_CANDIDATES[*]}) via native repos or Adoptium."
    exit 1
}

# Adoptium's package doesn't always register /usr/bin/java via
# alternatives on every distro release, so make sure it's on PATH.
register_java_alternative() {
    local rpm_name="$1" jhome
    jhome="$(rpm -ql "$rpm_name" 2>/dev/null | grep -m1 '/bin/java$' | xargs -r dirname | xargs -r dirname)"
    if [ -n "$jhome" ]; then
        alternatives --install /usr/bin/java java "${jhome}/bin/java" 20000 >> "$ACCESS_LOG" 2>> "$ERROR_LOG" || true
    fi
}

# Confirms the installed Java major version is one Druid 36.0.0
# actually supports, before we spend time downloading/configuring.
verify_java_version() {
    local jv
    jv="$(java -version 2>&1 | head -n1 | grep -oP '"\K[0-9]+')"
    local ok=0 v
    for v in "${JAVA_CANDIDATES[@]}"; do
        [ "$jv" == "$v" ] && ok=1
    done
    if [ "$ok" -ne 1 ]; then
        log "ERROR" "Installed Java major version is ${jv}, but Druid ${DRUID_VERSION} only supports ${JAVA_CANDIDATES[*]}. Aborting before install."
        exit 1
    fi
}

#----------------------------------------------------------------
# 4. VOLUME NAME PROMPT (reject root volume)
#----------------------------------------------------------------
ROOT_DEVICE="$(findmnt -no SOURCE / 2>/dev/null || true)"

prompt_volume() {
    while true; do
        read -rp "Enter the volume name mounted under /opt (e.g. 'ausiytic'), or 'root' to use the root volume: " VOLUME_NAME_RAW

        if [[ -z "$VOLUME_NAME_RAW" ]]; then
            echo "Volume name cannot be empty. Try again."
            continue
        fi

        # Normalize input so both a bare name ('ausiytic') and a full
        # path ('/opt/ausiytic', 'opt/ausiytic', 'ausiytic/') work the
        # same way, instead of double-prefixing to /opt//opt/ausiytic.
        VOLUME_NAME="$VOLUME_NAME_RAW"
        VOLUME_NAME="${VOLUME_NAME#/opt/}"   # strip leading /opt/
        VOLUME_NAME="${VOLUME_NAME#opt/}"    # strip leading opt/
        VOLUME_NAME="${VOLUME_NAME%/}"       # strip trailing slash

        if [[ "$VOLUME_NAME" == "root" || "$VOLUME_NAME" == "/" || -z "$VOLUME_NAME" ]]; then
            BASE_PATH="/opt"
            VOLUME_NAME="root"
            mkdir -p "$BASE_PATH"
            log "WARN" "Using the root volume for Druid install (BASE_PATH=$BASE_PATH). Not recommended for production - a dedicated data volume is preferred."
            break
        fi

        BASE_PATH="/opt/${VOLUME_NAME}"

        if [ "$VOLUME_NAME_RAW" != "$VOLUME_NAME" ]; then
            log "INFO" "Interpreted '$VOLUME_NAME_RAW' as volume name '$VOLUME_NAME' -> $BASE_PATH"
        fi

        if [ ! -d "$BASE_PATH" ]; then
            echo "Path '$BASE_PATH' does not exist. Please mount the volume at ${BASE_PATH} first, then re-run (or type 'root' to use the root volume instead)."
            continue
        fi

        VOL_DEVICE="$(findmnt -no SOURCE --target "$BASE_PATH" 2>/dev/null || true)"

        if [ -z "$VOL_DEVICE" ] || [ "$VOL_DEVICE" == "$ROOT_DEVICE" ]; then
            log "WARN" "'$BASE_PATH' resolves to the root filesystem device (${ROOT_DEVICE:-unknown}) rather than a dedicated mount. Proceeding anyway since root volume is permitted."
        fi

        log "INFO" "Using volume '$VOLUME_NAME' -> $BASE_PATH (device: ${VOL_DEVICE:-root fs})"
        break
    done
}

#----------------------------------------------------------------
# 5b. DRUID CONFIG PROMPTS (varies per server/project)
#----------------------------------------------------------------
prompt_druid_config() {
    echo ""
    echo "=== Metadata store configuration ==="
    echo "Press Enter on the host field to skip Postgres and use the built-in Derby metadata store instead (fine for standalone/testing)."
    ask "PostgreSQL host/IP" "" META_DB_HOST

    if [ -n "$META_DB_HOST" ]; then
        METADATA_TYPE="postgresql"
        ask "PostgreSQL port" "5432" META_DB_PORT
        ask "PostgreSQL database name" "druid" META_DB_NAME
        ask "PostgreSQL username" "druid" META_DB_USER
        ask "PostgreSQL password" "" META_DB_PASS "yes"
        META_DB_URI="jdbc:postgresql://${META_DB_HOST}:${META_DB_PORT}/${META_DB_NAME}"
        log "INFO" "Metadata store: PostgreSQL @ ${META_DB_HOST}:${META_DB_PORT}/${META_DB_NAME}"
    else
        METADATA_TYPE="derby"
        log "INFO" "Metadata store: Derby (local, embedded) - no external DB configured"
    fi

    echo ""
    echo "=== Deep storage configuration ==="
    echo "Press Enter on the account field to skip Azure Blob and use local disk storage instead (fine for standalone/testing)."
    ask "Azure storage account name" "" AZURE_STORAGE_ACCOUNT

    if [ -n "$AZURE_STORAGE_ACCOUNT" ]; then
        STORAGE_TYPE="azure"
        ask "Azure storage container" "druid" AZURE_STORAGE_CONTAINER
        ask "Azure storage key" "" AZURE_STORAGE_KEY "yes"
        log "INFO" "Deep storage: Azure Blob (account=${AZURE_STORAGE_ACCOUNT}, container=${AZURE_STORAGE_CONTAINER})"
    else
        STORAGE_TYPE="local"
        log "INFO" "Deep storage: local disk - no Azure account configured"
    fi

    echo ""
    echo "=== Security ==="
    echo "Press Enter to auto-generate random admin/internal passwords."
    ask "Druid console admin password" "$(openssl rand -base64 12 2>/dev/null || date +%s%N | sha256sum | head -c16)" ADMIN_INIT_PASSWORD "yes"
    ask "Druid internal client password" "$(openssl rand -base64 12 2>/dev/null || date +%s%N | sha256sum | head -c16)" INTERNAL_CLIENT_PASSWORD "yes"
    echo ""
    log "INFO" "Configuration collected. Proceeding with installation..."
}

#----------------------------------------------------------------
# 5c. REQUIRED EXTENSIONS (built from user's config choices)
#----------------------------------------------------------------
build_required_extensions() {
    # NOTE: druid-multi-stage-query is intentionally NOT listed here.
    # As of Druid 35+, MSQ is built into core and must be removed from
    # loadList - leaving it in can break startup on upgrade.
    REQUIRED_EXTENSIONS=(druid-basic-security druid-parquet-extensions druid-hdfs-storage druid-kafka-indexing-service druid-datasketches druid-s3-extensions)

    if [ "$STORAGE_TYPE" == "azure" ]; then
        REQUIRED_EXTENSIONS+=(druid-azure-extensions)
    fi
    if [ "$METADATA_TYPE" == "postgresql" ]; then
        REQUIRED_EXTENSIONS+=(postgresql-metadata-storage)
    fi

    LOAD_LIST_JSON="[$(printf '"%s",' "${REQUIRED_EXTENSIONS[@]}" | sed 's/,$//')]"
    log "INFO" "Required extensions: ${REQUIRED_EXTENSIONS[*]}"
}

setup_paths() {
    SOURCE="${BASE_PATH}/softwares"
    DRUID_BINARIES="${BASE_PATH}/apps/druid/binaries"
    DRUID_DATA="${BASE_PATH}/apps/druid/data"
    DRUID_LOGS_SL="${BASE_PATH}/apps/druid/logs"
    DRUID_LOG="${BASE_PATH}/logs/druid"
    DRUID_DATA_BKP="${BASE_PATH}/apps/druid/druid_bkp"

    for d in "$SOURCE" "$DRUID_BINARIES" "$DRUID_DATA" "$DRUID_LOG" "$DRUID_DATA_BKP"; do
        if [ -d "$d" ]; then
            log "INFO" "$d already exists"
        else
            mkdir -p "$d"
            log "INFO" "Created $d"
        fi
    done

    log "INFO" "Creating/refreshing symlink for log folder"
    ln -sfn "$DRUID_LOG" "$DRUID_LOGS_SL"
}

#----------------------------------------------------------------
# 6. SERVICE USER
#----------------------------------------------------------------
create_service_user() {
    if id "$DRUID_SERVICE_USER" >/dev/null 2>&1; then
        log "INFO" "User $DRUID_SERVICE_USER already exists"
    else
        useradd -r -m -s /sbin/nologin "$DRUID_SERVICE_USER" 2>/dev/null \
            || useradd -r -m -s /usr/sbin/nologin "$DRUID_SERVICE_USER"
        log "INFO" "Created service user $DRUID_SERVICE_USER"
    fi
}

#----------------------------------------------------------------
# 7. DOWNLOAD & EXTRACT DRUID (idempotent)
#----------------------------------------------------------------
download_and_install_druid() {
    cd "$SOURCE"

    if [ -f "$DRUID_TARBALL" ]; then
        log "INFO" "Tarball already downloaded, skipping download"
    else
        log "INFO" "Downloading Druid ${DRUID_VERSION}..."
        wget -q "$DRUID_DOWNLOAD_URL" -O "$DRUID_TARBALL" >> "$ACCESS_LOG" 2>> "$ERROR_LOG"
    fi

    if [ -d "apache-druid-${DRUID_VERSION}" ]; then
        log "INFO" "Tarball already extracted, skipping extraction"
    else
        log "INFO" "Extracting Druid tarball..."
        tar -xzf "$DRUID_TARBALL" >> "$ACCESS_LOG" 2>> "$ERROR_LOG"
    fi

    log "INFO" "Copying binaries to $DRUID_BINARIES"
    cp -r "apache-druid-${DRUID_VERSION}"/* "$DRUID_BINARIES"/

    if [ -x "${DRUID_BINARIES}/bin/verify-java" ]; then
        log "INFO" "Running Druid's own bin/verify-java to double-check Java compatibility"
        if ! "${DRUID_BINARIES}/bin/verify-java" >> "$ACCESS_LOG" 2>> "$ERROR_LOG"; then
            log "ERROR" "bin/verify-java reported an incompatible Java version. Check $ERROR_LOG for details."
            exit 1
        fi
    fi

    chown -R "${DRUID_SERVICE_USER}:${DRUID_SERVICE_USER}" "$BASE_PATH"
    log "INFO" "Druid install directory ownership set to $DRUID_SERVICE_USER"
}

#----------------------------------------------------------------
# 7b. PRUNE UNUSED EXTENSIONS
#----------------------------------------------------------------
# Druid's ExtensionsLoader scans (and partially initializes) every
# directory under extensions/ at startup, regardless of loadList,
# which is slow and CPU-heavy (e.g. druid-google-extensions alone
# drags in the full gRPC/Cloud SDK). Physically removing anything
# not in REQUIRED_EXTENSIONS makes startup fast and predictable.
prune_extensions() {
    local EXT_DIR="${DRUID_BINARIES}/extensions"

    if [ ! -d "$EXT_DIR" ]; then
        log "WARN" "Extensions directory not found at $EXT_DIR, skipping prune"
        return
    fi

    log "INFO" "Pruning unused extensions (keeping: ${REQUIRED_EXTENSIONS[*]})"
    local removed=0
    for dir in "$EXT_DIR"/*/; do
        local name
        name="$(basename "$dir")"
        local keep="no"
        for req in "${REQUIRED_EXTENSIONS[@]}"; do
            if [ "$name" == "$req" ]; then
                keep="yes"
                break
            fi
        done
        if [ "$keep" == "no" ]; then
            rm -rf "$dir"
            removed=$((removed + 1))
        fi
    done
    log "INFO" "Pruned $removed unused extension directories"
}

#----------------------------------------------------------------
# 8. CONFIGURATION FILES
#----------------------------------------------------------------
write_configs() {
    local CONF_ROOT="${DRUID_BINARIES}/conf/druid/single-server/micro-quickstart"
    local COMMON="${CONF_ROOT}/_common/common.runtime.properties"

    log "INFO" "Writing common.runtime.properties"

    local METADATA_BLOCK
    if [ "$METADATA_TYPE" == "postgresql" ]; then
        METADATA_BLOCK=$(cat <<EOF
druid.metadata.storage.type=postgresql
druid.metadata.storage.connector.connectURI=${META_DB_URI}
druid.metadata.storage.connector.user=${META_DB_USER}
druid.metadata.storage.connector.password=${META_DB_PASS}
EOF
)
    else
        METADATA_BLOCK=$(cat <<EOF
druid.metadata.storage.type=derby
druid.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/${DRUID_DATA}/metadata.db;create=true
druid.metadata.storage.connector.host=localhost
druid.metadata.storage.connector.port=1527
EOF
)
    fi

    local STORAGE_BLOCK
    local INDEXLOGS_BLOCK
    if [ "$STORAGE_TYPE" == "azure" ]; then
        STORAGE_BLOCK=$(cat <<EOF
druid.storage.type=azure
druid.azure.account=${AZURE_STORAGE_ACCOUNT}
druid.azure.container=${AZURE_STORAGE_CONTAINER}
druid.azure.key=${AZURE_STORAGE_KEY}
EOF
)
        INDEXLOGS_BLOCK=$(cat <<EOF
druid.indexer.logs.type=azure
druid.indexer.logs.container=${AZURE_STORAGE_CONTAINER}
druid.indexer.logs.prefix=indexlogs
EOF
)
    else
        STORAGE_BLOCK=$(cat <<EOF
druid.storage.type=local
druid.storage.storageDirectory=${DRUID_DATA}/segments
EOF
)
        INDEXLOGS_BLOCK=$(cat <<EOF
druid.indexer.logs.type=file
druid.indexer.logs.directory=${DRUID_DATA}/indexing-logs
EOF
)
        mkdir -p "${DRUID_DATA}/segments" "${DRUID_DATA}/indexing-logs"
    fi

    cat > "$COMMON" <<EOF
# Auto-generated by druid_install.sh on ${LOGTIME}
druid.extensions.loadList=${LOAD_LIST_JSON}

druid.host=localhost

druid.startup.logging.logProperties=true

druid.zk.service.host=localhost
druid.zk.paths.base=/druid

${METADATA_BLOCK}

${STORAGE_BLOCK}

${INDEXLOGS_BLOCK}

druid.selectors.indexing.serviceName=druid/overlord
druid.selectors.coordinator.serviceName=druid/coordinator

druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.server.metrics.ServiceStatusMonitor"]
druid.emitter=noop
druid.emitter.logging.logLevel=info

druid.indexing.doubleStorage=double

druid.server.hiddenProperties=["druid.s3.accessKey","druid.s3.secretKey","druid.metadata.storage.connector.password", "password", "key", "token", "pwd"]

druid.sql.enable=true
druid.sql.planner.useGroupingSetForExactDistinct=true

druid.lookup.enableLookupSyncOnStartup=false

druid.expressions.useStrictBooleans=true

druid.global.http.eagerInitialization=false

druid.auth.authenticatorChain=["MyBasicMetadataAuthenticator"]
druid.auth.authenticator.MyBasicMetadataAuthenticator.type=basic
druid.auth.authenticator.MyBasicMetadataAuthenticator.initialAdminPassword=${ADMIN_INIT_PASSWORD}
druid.auth.authenticator.MyBasicMetadataAuthenticator.initialInternalClientPassword=${INTERNAL_CLIENT_PASSWORD}
druid.auth.authenticator.MyBasicMetadataAuthenticator.credentialsValidator.type=metadata
druid.auth.authenticator.MyBasicMetadataAuthenticator.skipOnFailure=false
druid.auth.authenticator.MyBasicMetadataAuthenticator.authorizerName=MyBasicMetadataAuthorizer

druid.escalator.type=basic
druid.escalator.internalClientUsername=druid_system
druid.escalator.internalClientPassword=${INTERNAL_CLIENT_PASSWORD}
druid.escalator.authorizerName=MyBasicMetadataAuthorizer

druid.auth.authorizers=["MyBasicMetadataAuthorizer"]
druid.auth.authorizer.MyBasicMetadataAuthorizer.type=basic
EOF

    log "INFO" "Writing broker config"
    mkdir -p "${CONF_ROOT}/broker"
    cat > "${CONF_ROOT}/broker/jvm.config" <<'EOF'
-server
-Xms512m
-Xmx512m
-XX:MaxDirectMemorySize=768m
-XX:+ExitOnOutOfMemoryError
-XX:+UseG1GC
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
EOF
    cat > "${CONF_ROOT}/broker/common.runtime.properties" <<'EOF'
druid.service=druid/broker
druid.plaintextPort=8082

druid.server.http.numThreads=12

druid.broker.http.numConnections=10
druid.broker.http.maxQueuedBytes=5MiB

druid.processing.buffer.sizeBytes=100MiB
druid.processing.numMergeBuffers=2
druid.processing.tmpDir=var/druid/processing

druid.broker.cache.useCache=false
druid.broker.cache.populateCache=false
EOF

    log "INFO" "Writing coordinator-overlord config"
    mkdir -p "${CONF_ROOT}/coordinator-overlord"
    cat > "${CONF_ROOT}/coordinator-overlord/jvm.config" <<'EOF'
-server
-Xms256m
-Xmx256m
-XX:+ExitOnOutOfMemoryError
-XX:+UseG1GC
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
-Dderby.stream.error.file=var/druid/derby.log
EOF
    cat > "${CONF_ROOT}/coordinator-overlord/common.runtime.properties" <<'EOF'
druid.service=druid/coordinator
druid.plaintextPort=8081

druid.coordinator.startDelay=PT10S
druid.coordinator.period=PT5S
druid.manager.segments.pollDuration=PT5S

druid.coordinator.asOverlord.enabled=true
druid.coordinator.asOverlord.overlordService=druid/overlord

druid.indexer.queue.startDelay=PT5S
druid.indexer.storage.type=metadata
EOF

    log "INFO" "Writing historical config"
    mkdir -p "${CONF_ROOT}/historical"
    cat > "${CONF_ROOT}/historical/jvm.config" <<'EOF'
-server
-Xms2g
-Xmx2g
-XX:MaxDirectMemorySize=4g
-XX:+ExitOnOutOfMemoryError
-XX:+UseG1GC
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
EOF
    cat > "${CONF_ROOT}/historical/common.runtime.properties" <<EOF
druid.service=druid/historical
druid.plaintextPort=8083

druid.server.http.numThreads=30

druid.processing.buffer.sizeBytes=200MiB
druid.processing.numMergeBuffers=2
druid.processing.numThreads=4
druid.processing.tmpDir=var/druid/processing

druid.segmentCache.locations=[{"path":"${DRUID_DATA}/segment-cache","maxSize":"50g"}]

druid.historical.cache.useCache=true
druid.historical.cache.populateCache=true
druid.cache.type=caffeine
druid.cache.sizeInBytes=120MiB
EOF

    log "INFO" "Writing middleManager config"
    mkdir -p "${CONF_ROOT}/middleManager"
    cat > "${CONF_ROOT}/middleManager/jvm.config" <<'EOF'
-server
-Xms64m
-Xmx64m
-XX:+ExitOnOutOfMemoryError
-XX:+UseG1GC
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
EOF
    cat > "${CONF_ROOT}/middleManager/common.runtime.properties" <<EOF
druid.service=druid/middleManager
druid.plaintextPort=8091

druid.worker.capacity=3
druid.worker.baseTaskDirs=["var/druid/task"]

druid.indexer.runner.javaOptsArray=["-server","-Xms1g","-Xmx1g","-XX:MaxDirectMemorySize=1g","-Duser.timezone=UTC","-Dfile.encoding=UTF-8","-XX:+ExitOnOutOfMemoryError","-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager","--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED","--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED","--add-opens=java.base/java.lang=ALL-UNNAMED","--add-opens=java.base/java.io=ALL-UNNAMED","--add-opens=java.base/java.nio=ALL-UNNAMED","--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED","--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"]

druid.server.http.numThreads=30

druid.indexer.fork.property.druid.processing.numMergeBuffers=2
druid.indexer.fork.property.druid.processing.buffer.sizeBytes=100MiB
druid.indexer.fork.property.druid.processing.numThreads=1

druid.indexer.task.hadoopWorkingPath=var/druid/hadoop-tmp

druid.export.storage.baseDir=${DRUID_BINARIES}

druid.sql.enable=true
EOF

    log "INFO" "Writing router config"
    mkdir -p "${CONF_ROOT}/router"
    cat > "${CONF_ROOT}/router/jvm.config" <<'EOF'
-server
-Xms256m
-Xmx256m
-XX:+UseG1GC
-XX:MaxDirectMemorySize=128m
-XX:+ExitOnOutOfMemoryError
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
EOF
    cat > "${CONF_ROOT}/router/common.runtime.properties" <<'EOF'
druid.service=druid/router
druid.plaintextPort=8888

druid.router.http.numConnections=50
druid.router.http.readTimeout=PT5M
druid.router.http.numMaxThreads=30
druid.server.http.numThreads=30

druid.router.defaultBrokerServiceName=druid/broker
druid.router.coordinatorServiceName=druid/coordinator

druid.router.managementProxy.enabled=true
EOF

    chown -R "${DRUID_SERVICE_USER}:${DRUID_SERVICE_USER}" "$BASE_PATH"
    log "INFO" "All Druid configuration files written"

    if ! grep -qF "druid.extensions.loadList=${LOAD_LIST_JSON}" "$COMMON"; then
        log "ERROR" "Verification failed: loadList in $COMMON does not match expected value. Aborting."
        exit 1
    fi
    log "INFO" "Verified loadList in common.runtime.properties matches expected extensions"
}

#----------------------------------------------------------------
# 9. SYSTEMD SERVICE
#----------------------------------------------------------------
create_systemd_service() {
    local DRUID_SERVICE_FILE="/etc/systemd/system/druid.service"

    log "INFO" "Creating systemd unit at $DRUID_SERVICE_FILE"
    cat > "$DRUID_SERVICE_FILE" <<EOF
[Unit]
Description=Apache Druid server (micro-quickstart)
After=network.target multi-user.target

[Service]
Type=simple
User=${DRUID_SERVICE_USER}
WorkingDirectory=${DRUID_BINARIES}
ExecStart=${DRUID_BINARIES}/bin/start-micro-quickstart
Environment=DRUID_LOG_DIR=${DRUID_LOGS_SL}
Restart=on-failure
RestartSec=10
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

    log "INFO" "Reloading systemd daemon"
    systemctl daemon-reload

    log "INFO" "Enabling druid service for boot persistence"
    systemctl enable druid.service >> "$ACCESS_LOG" 2>> "$ERROR_LOG"
}

#----------------------------------------------------------------
# 10. FIREWALL (best-effort, non-fatal)
#----------------------------------------------------------------
open_firewall_ports() {
    local ports=(8081 8082 8083 8088 8090 8091 8888)
    if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
        for p in "${ports[@]}"; do ufw allow "${p}/tcp" >> "$ACCESS_LOG" 2>> "$ERROR_LOG" || true; done
        log "INFO" "Opened Druid ports via ufw"
    elif command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld; then
        for p in "${ports[@]}"; do firewall-cmd --permanent --add-port="${p}/tcp" >> "$ACCESS_LOG" 2>> "$ERROR_LOG" || true; done
        firewall-cmd --reload >> "$ACCESS_LOG" 2>> "$ERROR_LOG" || true
        log "INFO" "Opened Druid ports via firewalld"
    else
        log "INFO" "No active firewall manager detected, skipping firewall step"
    fi
}

#----------------------------------------------------------------
# 11. START & VERIFY
#----------------------------------------------------------------
start_and_verify() {
    if systemctl is-active --quiet druid.service \
        && curl -s -o /dev/null -w "%{http_code}" "http://localhost:8888/status/health" 2>/dev/null | grep -q "200"; then
        log "INFO" "druid.service is already active and healthy - no restart needed"
    else
        log "INFO" "Starting druid service"
        systemctl restart druid.service

        log "INFO" "Waiting for Druid router (port 8888) to become healthy..."
        local retries=30
        local ok=0
        for ((i=1; i<=retries; i++)); do
            if curl -s -o /dev/null -w "%{http_code}" "http://localhost:8888/status/health" 2>/dev/null | grep -q "200"; then
                ok=1
                break
            fi
            sleep 10
        done

        if [ "$ok" -eq 1 ]; then
            log "INFO" "Druid is UP. Console: http://$(hostname -I | awk '{print $1}'):8888"
        else
            log "ERROR" "Druid did not become healthy in time. Check: journalctl -u druid -f"
            systemctl status druid.service --no-pager >> "$ERROR_LOG" 2>&1 || true
            exit 1
        fi
    fi

    if ! systemctl is-active --quiet druid.service; then
        log "ERROR" "druid.service is not active after startup."
        exit 1
    fi
    log "INFO" "druid.service is active and enabled: $(systemctl is-enabled druid.service)"
}

#----------------------------------------------------------------
# MAIN
#----------------------------------------------------------------
main() {
    log "INFO" "=== Druid ${DRUID_VERSION} automated installation started ==="
    detect_os
    install_prereqs

    load_state
    if [ "$STATE_EXISTS" == "no" ]; then
        prompt_volume
        prompt_druid_config
    else
        log "INFO" "Re-using saved volume '$VOLUME_NAME' -> $BASE_PATH and saved metadata/storage/credential settings (not re-prompting)."
    fi

    build_required_extensions
    setup_paths
    create_service_user

    NEED_INSTALL="yes"
    if [ "$STATE_EXISTS" == "yes" ] \
        && [ "${INSTALLED_DRUID_VERSION:-}" == "$DRUID_VERSION" ] \
        && [ -x "${DRUID_BINARIES}/bin/start-micro-quickstart" ]; then
        NEED_INSTALL="no"
        log "INFO" "Druid ${DRUID_VERSION} is already installed at $DRUID_BINARIES - skipping download/extract/reconfigure. Use --reconfigure to force a fresh install, or bump DRUID_VERSION to upgrade."
    fi

    if [ "$NEED_INSTALL" == "yes" ]; then
        download_and_install_druid
        prune_extensions
        write_configs
    fi

    create_systemd_service
    open_firewall_ports
    persist_state
    start_and_verify

    log "INFO" "=== Druid installation completed successfully ==="
    echo ""
    echo "Access log: $ACCESS_LOG"
    echo "Error log : $ERROR_LOG"
}

main "$@"

